import { pgTable, text, integer, boolean, timestamp, real, jsonb, uuid } from "drizzle-orm/pg-core";

export const schools = pgTable("schools", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  division: text("division").notNull(),
  conference: text("conference").notNull(),
  state: text("state"),
  priorityTier: text("priority_tier").notNull(),
  olNeedScore: integer("ol_need_score").default(0),
  whyJacob: text("why_jacob"),
  rosterUrl: text("roster_url"),
  staffUrl: text("staff_url"),
  officialXHandle: text("official_x_handle"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const coaches = pgTable("coaches", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  title: text("title"),
  schoolId: text("school_id").references(() => schools.id),
  schoolName: text("school_name").notNull(),
  division: text("division").notNull(),
  conference: text("conference"),
  xHandle: text("x_handle"),
  dmOpen: boolean("dm_open").default(false),
  followStatus: text("follow_status").default("not_followed"),
  dmStatus: text("dm_status").default("not_sent"),
  priorityTier: text("priority_tier").notNull(),
  olNeedScore: integer("ol_need_score").default(0),
  xActivityScore: integer("x_activity_score").default(0),
  lastEngaged: timestamp("last_engaged"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const posts = pgTable("posts", {
  id: uuid("id").defaultRandom().primaryKey(),
  content: text("content").notNull(),
  pillar: text("pillar").notNull(),
  hashtags: jsonb("hashtags").$type<string[]>().default([]),
  mediaUrl: text("media_url"),
  scheduledFor: timestamp("scheduled_for"),
  bestTime: text("best_time"),
  status: text("status").default("draft"),
  xPostId: text("x_post_id"),
  impressions: integer("impressions").default(0),
  engagements: integer("engagements").default(0),
  engagementRate: real("engagement_rate").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const dmMessages = pgTable("dm_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  coachId: uuid("coach_id").references(() => coaches.id),
  coachName: text("coach_name").notNull(),
  schoolName: text("school_name").notNull(),
  templateType: text("template_type").notNull(),
  content: text("content").notNull(),
  status: text("status").default("drafted"),
  sentAt: timestamp("sent_at"),
  respondedAt: timestamp("responded_at"),
  responseContent: text("response_content"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const engagementLog = pgTable("engagement_log", {
  id: uuid("id").defaultRandom().primaryKey(),
  eventType: text("event_type").notNull(),
  coachId: uuid("coach_id").references(() => coaches.id),
  coachName: text("coach_name"),
  schoolName: text("school_name"),
  postId: uuid("post_id").references(() => posts.id),
  details: text("details"),
  timestamp: timestamp("timestamp").defaultNow(),
});

export const profileAudits = pgTable("profile_audits", {
  id: uuid("id").defaultRandom().primaryKey(),
  date: timestamp("date").defaultNow(),
  photoQuality: boolean("photo_quality").default(false),
  headerImage: boolean("header_image").default(false),
  bioCompleteness: boolean("bio_completeness").default(false),
  pinnedPost: boolean("pinned_post").default(false),
  postCadence: boolean("post_cadence").default(false),
  pillarDistribution: boolean("pillar_distribution").default(false),
  engagementRate: boolean("engagement_rate_check").default(false),
  coachFollowCount: boolean("coach_follow_count").default(false),
  dmLog: boolean("dm_log").default(false),
  constitutionCompliance: boolean("constitution_compliance").default(false),
  totalScore: integer("total_score").default(0),
  recommendations: jsonb("recommendations").$type<string[]>().default([]),
});

export const competitorRecruits = pgTable("competitor_recruits", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  xHandle: text("x_handle"),
  position: text("position"),
  classYear: integer("class_year"),
  school: text("school"),
  state: text("state"),
  height: text("height"),
  weight: text("weight"),
  followerCount: integer("follower_count").default(0),
  postCadence: real("post_cadence").default(0),
  engagementRate: real("engagement_rate").default(0),
  topContentTypes: jsonb("top_content_types").$type<string[]>().default([]),
  schoolInterestSignals: jsonb("school_interest_signals").$type<string[]>().default([]),
  lastUpdated: timestamp("last_updated").defaultNow(),
});

export const analyticsSnapshots = pgTable("analytics_snapshots", {
  id: uuid("id").defaultRandom().primaryKey(),
  date: timestamp("date").defaultNow(),
  totalFollowers: integer("total_followers").default(0),
  coachFollows: integer("coach_follows").default(0),
  dmsSent: integer("dms_sent").default(0),
  dmResponseRate: real("dm_response_rate").default(0),
  postsPublished: integer("posts_published").default(0),
  avgEngagementRate: real("avg_engagement_rate").default(0),
  profileVisits: integer("profile_visits").default(0),
  auditScore: integer("audit_score").default(0),
});

// ============ RECRUITING INTELLIGENCE TABLES ============

export const hudlProfiles = pgTable("hudl_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  profileId: text("profile_id").notNull().unique(),
  profileUrl: text("profile_url").notNull(),
  athleteName: text("athlete_name").notNull(),
  position: text("position"),
  positionDetails: jsonb("position_details").$type<string[]>().default([]),
  height: text("height"),
  weight: text("weight"),
  gradYear: integer("grad_year"),
  highSchool: text("high_school"),
  city: text("city"),
  state: text("state"),
  jerseyNumber: text("jersey_number"),
  gpa: text("gpa"),
  satScore: integer("sat_score"),
  actScore: integer("act_score"),
  highlightReels: jsonb("highlight_reels").$type<{ title: string; url: string; duration: string | null; viewCount: number | null; createdAt: string | null }[]>().default([]),
  gameFilmCount: integer("game_film_count").default(0),
  totalPlaysTagged: integer("total_plays_tagged").default(0),
  recruitingOptIn: boolean("recruiting_opt_in").default(false),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  bio: text("bio"),
  profileViews: integer("profile_views"),
  scrapeSource: text("scrape_source").default("jina"),
  rawMarkdown: text("raw_markdown"),
  scrapedAt: timestamp("scraped_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const tweetPatterns = pgTable("tweet_patterns", {
  id: uuid("id").defaultRandom().primaryKey(),
  tweetId: text("tweet_id").notNull(),
  authorHandle: text("author_handle").notNull(),
  authorName: text("author_name"),
  tweetText: text("tweet_text").notNull(),
  patternType: text("pattern_type").notNull(),
  confidence: real("confidence").default(0),
  schoolMentions: jsonb("school_mentions").$type<string[]>().default([]),
  coachMentions: jsonb("coach_mentions").$type<string[]>().default([]),
  hashtags: jsonb("hashtags").$type<string[]>().default([]),
  likes: integer("likes").default(0),
  retweets: integer("retweets").default(0),
  replies: integer("replies").default(0),
  impressions: integer("impressions").default(0),
  tweetCreatedAt: timestamp("tweet_created_at"),
  analyzedAt: timestamp("analyzed_at").defaultNow(),
});

export const offerEvents = pgTable("offer_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  athleteHandle: text("athlete_handle").notNull(),
  athleteName: text("athlete_name"),
  schoolName: text("school_name").notNull(),
  schoolHandle: text("school_handle"),
  coachName: text("coach_name"),
  coachHandle: text("coach_handle"),
  offerDate: timestamp("offer_date"),
  sourceTweetId: text("source_tweet_id"),
  sourceTweetUrl: text("source_tweet_url"),
  verified: boolean("verified").default(false),
  division: text("division"),
  conference: text("conference"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const coachBehaviorProfiles = pgTable("coach_behavior_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  coachId: uuid("coach_id").references(() => coaches.id),
  coachName: text("coach_name").notNull(),
  schoolName: text("school_name").notNull(),
  division: text("division"),
  conference: text("conference"),
  engagementStyle: text("engagement_style"),
  dmOpenProbability: real("dm_open_probability").default(0),
  followBackProbability: real("follow_back_probability").default(0),
  avgResponseTime: real("avg_response_time"),
  tweetFrequency: real("tweet_frequency").default(0),
  peakActivityHours: jsonb("peak_activity_hours").$type<number[]>().default([]),
  commonHashtags: jsonb("common_hashtags").$type<string[]>().default([]),
  interactsWithRecruits: boolean("interacts_with_recruits").default(false),
  bestApproachMethod: text("best_approach_method"),
  bestApproachSteps: jsonb("best_approach_steps").$type<string[]>().default([]),
  estimatedResponseRate: real("estimated_response_rate").default(0),
  optimalContactMonths: jsonb("optimal_contact_months").$type<number[]>().default([]),
  optimalContactHours: jsonb("optimal_contact_hours").$type<number[]>().default([]),
  lastUpdated: timestamp("last_updated").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const intelligenceScores = pgTable("intelligence_scores", {
  id: uuid("id").defaultRandom().primaryKey(),
  athleteId: text("athlete_id").notNull(),
  athleteName: text("athlete_name").notNull(),
  overallScore: integer("overall_score").default(0),
  filmScore: integer("film_score").default(0),
  socialPresenceScore: integer("social_presence_score").default(0),
  recruitingMomentumScore: integer("recruiting_momentum_score").default(0),
  academicScore: integer("academic_score").default(0),
  physicalProfileScore: integer("physical_profile_score").default(0),
  tierProjection: text("tier_projection"),
  projectedTier: text("projected_tier"),
  dataCompleteness: real("data_completeness").default(0),
  recommendations: jsonb("recommendations").$type<{ priority: string; category: string; title: string; description: string; actionItems: string[] }[]>().default([]),
  calculatedAt: timestamp("calculated_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const scrapeJobs = pgTable("scrape_jobs", {
  id: uuid("id").defaultRandom().primaryKey(),
  type: text("type").notNull(),
  targetUrl: text("target_url").notNull(),
  status: text("status").default("pending"),
  result: jsonb("result"),
  error: text("error"),
  retryCount: integer("retry_count").default(0),
  completedAt: timestamp("completed_at"),
  createdAt: timestamp("created_at").defaultNow(),
});
